# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=300)),
                ('expiry_date', models.DateTimeField(verbose_name='expiry date')),
            ],
        ),
        migrations.CreateModel(
            name='SNlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.BooleanField()),
                ('read', models.BooleanField()),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=40)),
                ('enr_no', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suscribed', models.BooleanField()),
                ('sus_since', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.Category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.Student')),
            ],
        ),
        migrations.AddField(
            model_name='snlink',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.Student'),
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.Student'),
        ),
        migrations.AddField(
            model_name='category',
            name='suscriber',
            field=models.ManyToManyField(through='bulletin.Subscription', to='bulletin.Student'),
        ),
    ]
