# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0003_auto_20170404_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bulletin.Notice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='starred',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
