# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0004_auto_20170404_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='starred',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribed',
        ),
    ]
